### ISSUE TITLE
Option to load a database from a url

### ISSUE THREAD

**Issue by isthisthat** [lunu-bounir/sqlite-manager#5]
Hello, I would like to open an sqlite file that's hosted in an S3 bucket (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-examples.html). Would you consider adding an option for that? Thanks a lot!

**Comment by lunu-bounir** [comment]
As of the next release you can load a db using `db_load('http://..../database.sqlite', "my_db_name")` command

**Comment by isthisthat** [comment]
That's fantastic, thanks! When can we expect a release?

**Comment by lunu-bounir** [comment]
currently blocked by https://github.com/mozilla/addons/issues/908
